{ pkgs, ... }:
{
    home.packages = [ pkgs.wallust ];

    # Main wallust config
    xdg.configFile."wallust/wallust.toml".text = ''
        backend = "full"
        color_space = "lch"
        palette = "dark16"
        threshold = 20
        # Check spelling: these must match wallust's field names exactly
        check_contrast = true

        # Template definitions
        [[templates]]
        template = "waybar-colors.css"
        target = "~/.config/waybar/colors.css"

        [[templates]]
        template = "foot-colors.ini"
        target = "~/.cache/wallust/foot-colors.ini"

        [[templates]]
        template = "fuzzel-colors.ini"
        target = "~/.cache/wallust/fuzzel-colors.ini"

        [[templates]]
        template = "mako-colors"
        target = "~/.cache/wallust/mako-colors"

        [[templates]]
        template = "discord.css"
        target = "~/.config/vesktop/themes/wallust.css"

        [[templates]]
        template = "hyprland-colors.conf"
        target = "~/.cache/wallust/hyprland-colors.conf"

        [[templates]]
        template = "zen-colors.css"
        target = "~/.cache/wallust/zen-colors.css"
    '';

    # ── Waybar CSS template ──────────────────────────────────────────────
    xdg.configFile."wallust/templates/waybar-colors.css".text = ''
        @define-color background  {{background}};
        @define-color foreground  {{foreground}};
        @define-color cursor      {{cursor}};
        @define-color color0      {{color0}};
        @define-color color1      {{color1}};
        @define-color color2      {{color2}};
        @define-color color3      {{color3}};
        @define-color color4      {{color4}};
        @define-color color5      {{color5}};
        @define-color color6      {{color6}};
        @define-color color7      {{color7}};
        @define-color color8      {{color8}};
        @define-color color9      {{color9}};
        @define-color color10     {{color10}};
        @define-color color11     {{color11}};
        @define-color color12     {{color12}};
        @define-color color13     {{color13}};
        @define-color color14     {{color14}};
        @define-color color15     {{color15}};
    '';

    # ── Foot colors template ─────────────────────────────────────────────
    xdg.configFile."wallust/templates/foot-colors.ini".text = ''
        [colors]
        background={{background | strip_hash}}
        foreground={{foreground | strip_hash}}
        regular0={{color0 | strip_hash}}
        regular1={{color1 | strip_hash}}
        regular2={{color2 | strip_hash}}
        regular3={{color3 | strip_hash}}
        regular4={{color4 | strip_hash}}
        regular5={{color5 | strip_hash}}
        regular6={{color6 | strip_hash}}
        regular7={{color7 | strip_hash}}
        bright0={{color8 | strip_hash}}
        bright1={{color9 | strip_hash}}
        bright2={{color10 | strip_hash}}
        bright3={{color11 | strip_hash}}
        bright4={{color12 | strip_hash}}
        bright5={{color13 | strip_hash}}
        bright6={{color14 | strip_hash}}
        bright7={{color15 | strip_hash}}
    '';

    # ── Fuzzel colors template ───────────────────────────────────────────
    xdg.configFile."wallust/templates/fuzzel-colors.ini".text = ''
        [colors]
        background={{background | strip_hash}}cc
        text={{foreground | strip_hash}}ff
        match={{color2 | strip_hash}}ff
        selection={{color1 | strip_hash}}cc
        selection-text={{background | strip_hash}}ff
        selection-match={{color2 | strip_hash}}ff
        border={{color1 | strip_hash}}ff
    '';

    # ── Mako colors template ─────────────────────────────────────────────
    xdg.configFile."wallust/templates/mako-colors".text = ''
        background-color={{background}}cc
        text-color={{foreground}}ff
        border-color={{color1}}ff

        [urgency=low]
        border-color={{color2}}ff

        [urgency=high]
        border-color={{color9}}ff
        background-color={{color1}}cc
    '';

    # ── Hyprland border colors template ──────────────────────────────────
    xdg.configFile."wallust/templates/hyprland-colors.conf".text = ''
        general {
          col.active_border = rgba({{color1 | strip_hash}}ff) rgba({{color2 | strip_hash}}ff) 45deg
          col.inactive_border = rgba({{color0 | strip_hash}}aa)
        }
        decoration {
          col.shadow = rgba({{color0 | strip_hash}}ee)
        }
    '';

    # ── Discord/Vesktop CSS template ─────────────────────────────────────
    xdg.configFile."wallust/templates/discord.css".text = ''
        /**
         * @name Wallust Theme
         * @description Auto-generated by wallust from wallpaper colors
         */
        :root {
          --background-primary:           {{background}};
          --background-secondary:         {{color0}};
          --background-secondary-alt:     {{color8}};
          --background-tertiary:          {{color0}};
          --background-accent:            {{color1}};
          --background-floating:          {{color0}};
          --background-mobile-primary:    {{background}};
          --background-mobile-secondary:  {{color0}};
          --background-modifier-hover:    {{color1}}33;
          --background-modifier-active:   {{color1}}55;
          --background-modifier-selected: {{color1}}44;
          --channeltextarea-background:   {{color8}};
          --text-normal:         {{foreground}};
          --text-muted:          {{color7}};
          --text-link:           {{color4}};
          --interactive-normal:  {{color7}};
          --interactive-hover:   {{foreground}};
          --interactive-active:  {{foreground}};
          --interactive-muted:   {{color8}};
          --brand-experiment:    {{color1}};
          --brand-experiment-560: {{color1}};
        }
    '';

    # ── Zen Browser CSS variables template ───────────────────────────────
    xdg.configFile."wallust/templates/zen-colors.css".text = ''
        :root {
          --zen-primary-color:          {{color1}};
          --zen-secondary-color:        {{color2}};
          --toolbar-bgcolor:            {{background}};
          --toolbar-color:              {{foreground}};
          --toolbarbutton-hover-background: {{color8}};
          --toolbarbutton-active-background: {{color1}}44;
          --urlbar-background:          {{color0}};
          --urlbar-color:               {{foreground}};
          --tab-selected-bgcolor:       {{color1}};
          --tab-selected-color:         {{background}};
          --sidebar-background-color:   {{color0}};
        }
    '';

    # ── Wallpaper setter script ───────────────────────────────────────────
    home.file.".local/bin/set-wallpaper.sh" = {
        executable = true;
        text = ''
            #!/usr/bin/env bash
            set -euo pipefail

            WALLPAPER="$(realpath "$1")"

            if [[ ! -f "$WALLPAPER" ]]; then
              echo "Error: file not found: $WALLPAPER" >&2
              exit 1
            fi

            # Save path for lock screen and login restore
            echo "$WALLPAPER" > ~/.cache/wallust/last-wallpaper

            # Generate palette and render all templates
            wallust run "$WALLPAPER"

            # Hot-swap wallpaper via hyprpaper IPC (no restart needed)
            hyprctl hyprpaper preload "$WALLPAPER"
            hyprctl hyprpaper wallpaper ",$WALLPAPER"

            # Reload waybar (SIGUSR2 = reload config+style, SIGUSR1 = toggle)
            pkill -SIGUSR2 waybar 2>/dev/null || true

            # Reload mako
            makoctl reload 2>/dev/null || true

            # Source hyprland color overrides
            if [[ -f ~/.cache/wallust/hyprland-colors.conf ]]; then
              hyprctl reload 2>/dev/null || true
            fi

            # Notify
            notify-send \
              --icon="$WALLPAPER" \
              --app-name="Wallpaper" \
              "Theme applied" \
              "$(basename "$WALLPAPER")" \
              2>/dev/null || true
        '';
    };

    # Ensure cache dir and default wallpaper file exist
    home.file.".cache/wallust/.keep".text = "";
}
